services:
  nats:
    image: nats:latest
    ports:
      - "8222:8222"
      - "4222:4222"
    command: "--name nats --http_port 8222 --js"
    networks: ["nats"]
networks:
    nats:
      name: nats